linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - golint
    - misspell
    - gocyclo
    - bodyclose
    - unconvert
    - goconst
    - goimports
    - unparam
    - whitespace
    - godot

issues:
  exclude-use-default: false

  exclude-rules:
    - path: cmd/powbench/runner/runner_test.go
      linters:
        - unused

run:
  timeout: 30m
  skip-files:
    - gateway/assets.go

service:
  golangci-lint-version: 1.27.x # use the fixed version to not introduce new linters unexpectedly
    
