version: '3.7'

services:

  powergate:
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    restart: unless-stopped

  ipfs:
    entrypoint: ""
    command: /bin/sh -c "/usr/local/bin/start_ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"*\"]' && /usr/local/bin/start_ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"POST\",\"GET\",\"PUT\"]' && /usr/local/bin/start_ipfs daemon  --enable-pubsub-experiment"
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:ntwk-calibration-8.13.1.f0942
    ports:
      - 7777:7777
      - 1234:1234
    environment:
      - TEXLOTUSDEVNET_SPEED=500
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
