version: '3.7'

volumes:
   pow-devnet-shared:

services:
  
  powergate:
    build:
      context: ../
      dockerfile: cmd/powd/Dockerfile
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    volumes:
      - pow-devnet-shared:/tmp/powergate
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.5.1
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:sha-f8988b8
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
      - TEXLOTUSDEVNET_BIGSECTORS=true
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
    volumes:
     - pow-devnet-shared:/tmp/powergate
