name: Docker Image
on:
  release:
    types: [published]
  push:
    branches:
      - master
jobs:
  docker:
    name: Docker publishing
    runs-on: self-hosted
    steps:
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          repository: textile/powergate
          tag_with_ref: true
          tag_with_sha: true
