name: Ensure Docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ensure-pow-docs:
    name: Ensure pow docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Generate docs
        run: make docs-pow
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: exit 1
