name: Publish Docker Compose Files
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  publish_docker:
    name: Publish Docker Compose Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Update powergate image version
        run: sed -i.bak 's/latest/${{steps.latesttag.outputs.tag}}/g' docker/powergate-image.yaml
      - name: Print image
        run: cat docker/powergate-image.yaml
      - name: Update Makefile
        run: sed -i.bak 's/powergate-build-context/powergate-image/g' docker/Makefile
      - name: Print Makefile
        run: cat docker/Makefile
      - name: Remove sed backups
        run: rm -rf docker/*.bak
      - name: Create archive
        run: zip -r docker.zip docker
      # - name: Upload artifacts to release
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: 'docker.zip'
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
