name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install OpenCL
        run: sudo apt-get update && sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: make test
