name: Tests
on:
  push:
    branches:
      - master
      - jsign/pg5
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: make test
