name: Tests
on:
  push:
    branches:
      - master
      - jsign/fastapi2
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13.8"
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install OpenCL
        run: sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: make test
